name: 'Merge Request Labelled'
on:
  pull_request:
    types: [closed]
jobs:
  pr-closed:
    name: PR Closed
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: |
        sh -c 'env | sort'
    - name: Github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: "echo $GITHUB_CONTEXT"
